### PR TITLE
LPS-55368

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @mikakoivisto,

Attached is an update for http://issues.liferay.com/browse/LPS-55368.  We have added a text area for allowed service signatures and disallowed service signatures.

There are a few things that are left to be done which we need some backend help to be completed.
1. Saving the textarea data to the database.
2. Fetching the textarea data from the database.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mikakoivisto** [comment]
Hey @jonmak08  did you test the UI and were you able to get it to autocomplete? 

Last week there was some issues with master but now I can at least see the javascript on the page but I can't get it to provide any autocompletion on either textareas and looking at the code I don't see how it even could try to autocomplete the service method names. It just doesn't add up.

**Comment by jonmak08** [comment]
Hey @mikakoivisto,

I just tested the changes rebased on master and I was able to get the autocomplete working.  Below is a screenshot.

sap

Please let me know if you have any questions.  Thanks!

**Comment by mikakoivisto** [comment]
There’s no + or - in the syntax you just type the className. How about the methods on the class? After you put a # after the className it should suggest methods on that class.

**Comment by mikakoivisto** [comment]
I'm rejecting it because it's not quite fully functional i.e. it doesn't suggest methods. Don't worry about the disallowed service signatures it will be implemented in another improvement ticket so I will cut it out anyways.

**Comment by jonmak08** [comment]
Hey @mikakoivisto,

When I was talking to @david-truong, he mentioned we could use the +/- in the text area for the classNames.  For autocomplete to work, we need a trigger to activate it.  I will look into activating the autocomplete when we start typing.

If the method suggestions are required, then what is to differentiate the autocomplete from showing class names or methods?

I am just curious what you had in mind about how they would be separated and entered via the text box?

Thanks!

**Comment by mikakoivisto** [comment]
Okay he should have consulted me first about the +/- as it will render the line invalid so it will never match anything and thus nothing will be permitted. I'm going to refer you to the doc Jesse wrote so you can understand what is expected to be in the box. 

https://github.com/jrao/liferay-docs/blob/cc5e20ebee13bca3707099483a3d3fe65a64f536/discover/new-articles/service-access-policies.markdown

I'd expect it to start suggesting when anything is typed in the box like google does and when it encounters # -mark then anything after it is considered a method of the class defined before it.

**Comment by david-truong** [comment]
Sorry Jon,  I meant that as a future enhancement.  Sorry I wasn't clear.

On Thu, Sep 10, 2015 at 11:37 AM, Mika Koivisto <notifications@github.com>
wrote:

> Okay he should have consulted me first about the +/- as it will render the
> line invalid so it will never match anything and thus nothing will be
> permitted. I'm going to refer you to the doc Jesse wrote so you can
> understand what is expected to be in the box.
>
>
> https://github.com/jrao/liferay-docs/blob/cc5e20ebee13bca3707099483a3d3fe65a64f536/discover/new-articles/service-access-policies.markdown
>
> I'd expect it to start suggesting when anything is typed in the box like
> google does and when it encounters # -mark then anything after it is
> considered a method of the class defined before it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikakoivisto/liferay-portal/pull/99#issuecomment-139304879>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/mjbradford89/liferay-portal/pull/63

**Pull request closed without merging**
