### PR TITLE
LPS-67491 Settings framework doesn't respect Meta.AD annotation id property anymore

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-67491](https://issues.liferay.com/browse/LPS-67491).<br><br>Hey @mikakoivisto, I made changes according to @JorgeFerrer 's comments.  I included your changes for returning the correct types, and I think I covered all the cases.  Will you please review my work and test to make sure the solution still works in your case?  Thanks!<br><br>/cc @jorgeferrer @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Hey @mikakoivisto, any word on testing this?

**Comment by mikakoivisto** [comment]
Thanks. Sent to Jorge https://github.com/JorgeFerrer/liferay-portal/pull/794

**Pull request closed without merging**
