### PR TITLE
[TECHNICAL SUPPORT] LPS-66165 ProtectedObjectInputStream only tries to resolve the class on the ContextClassloader

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-66165

Hi Mika,

The issue cannot be reproduced on master with the provided steps (read the the description), though the code is the same, so Norbi thought it was worth to push the changes to master also.

I'm also forwarding the equivalent fix for 62x shortly.

Regards,
Tibor

---

Author: @NorbertKocsis 
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Mika,

I was wondering if you had the time to review this pull.

Thanks,
Tibor

@mikakoivisto

**Comment by mikakoivisto** [comment]
Sorry for the delay. The fix is incorrect. SerializableUtil.clone() should take the objects classloader and pass it to deserialize method so that correct classloader is used. I'm fairly certain that we either did the same thing in another place or discussed it.

**Comment by lipusz** [comment]
Hi Mika,

So you're saying not POIS but SerializableUtil is the place @Norbert should fix this?

@mikakoivisto

**Comment by mikakoivisto** [comment]
Yes, that is correct. In the clone method just grab the classloader of the object that is being cloned. Then it should work no matter which classloader loaded it in the first place.

**Comment by lipusz** [comment]
Like this?

````java
	public static Object clone(Object object) {
		Class clazz = object.getClass();

		return deserialize(serialize(object), clazz.getClassLoader());
	}
```

Got it!

@NorbertKocsis: please, resend to Mike with the updated fix after testing it!

**Comment by mikakoivisto** [comment]
yep that seems correct.

**Comment by lipusz** [comment]
Thx! We'll resend shortly.

**Comment by norbert** [comment]
@lipusz wrong @norbert.

**Comment by lipusz** [comment]
Fixed. Sorry about that @norbert :+1:

**Comment by lipusz** [comment]
See: https://github.com/mikakoivisto/liferay-portal/pull/127

**Pull request closed without merging**
