### PR TITLE
LPS-58774 As a user I would like to see a warning message when my password reset link has expired

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-58774](https://issues.liferay.com/browse/LPS-58774).<br><br>/cc @pei-jung, @lipusz, @JorgeFerrer

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Guys,

I don't think it will work without modifying the UpdatePasswordAction:

````java
public class UpdatePasswordAction extends Action {

	@Override
	public ActionForward execute(
			ActionMapping actionMapping, ActionForm actionForm,
			HttpServletRequest request, HttpServletResponse response)
		throws Exception {

		ThemeDisplay themeDisplay = (ThemeDisplay)request.getAttribute(
			WebKeys.THEME_DISPLAY);

		Ticket ticket = getTicket(request);

		if (!themeDisplay.isSignedIn() && (ticket == null)) {
			return actionMapping.findForward(
				ActionConstants.COMMON_REFERER_JSP);
		}
// ...

	protected Ticket getTicket(HttpServletRequest request) {
		String ticketKey = ParamUtil.getString(request, "ticketKey");

		if (Validator.isNull(ticketKey)) {
			return null;
		}

		try {
			Ticket ticket = TicketLocalServiceUtil.getTicket(ticketKey);

			if (ticket.getType() != TicketConstants.TYPE_PASSWORD) {
				return null;
			}

			if (!ticket.isExpired()) {
				return ticket;
			}

			TicketLocalServiceUtil.deleteTicket(ticket);
		}
		catch (Exception e) {
		}

		return null;
	}
//...
````
update_password.jsp is not included if the ticket is expired, instead, we land in common referer.

Cheers,
Tibor

@drewbrokke @mikakoivisto

**Comment by mikakoivisto** [comment]
Yes, this will have the issue Tibor described and also we are deleting the old ticket if a user requests a ticket twice so it won't be expired but rather doesn't exist at all so that's a case that also has to be dealt with. So maybe @JorgeFerrer want's to chime in how we want to deal with that case. 

In addition to this forgot password seems to be broken in master I had to turn off reminder queries before it even sent the password reset ticket email. So I don't know how you managed to test this.

**Comment by mikakoivisto** [comment]
Talked also to Tomas and it should be fine if we give a generic message on both cases that the ticket is either invalid or expired. We'll need similar for email verification and everything else that uses tickets.

**Comment by JorgeFerrer** [comment]
Sorry for not answering earlier. I'm also ok with providing a generic message.

**Pull request closed without merging**
