### PR TITLE
LPS-58774 As a user I would like to see a warning message when my password reset link has expired

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-58774](https://issues.liferay.com/browse/LPS-58774).<br><br>I have made the revisions suggested in the previous pull request.  UpdatePasswordAction will now redirect to update_password.jsp when the ticket is either expired or missing. /cc @pei-jung, @lipusz, @JorgeFerrer

### CODE REVIEW

**Comment by lipusz** [comment]
To simplify the UI, couldn't we just add

````diff
 			<aui:input name="<%= WebKeys.REFERER %>" type="hidden" value="<%= referer %>" />
 			<aui:input name="ticketKey" type="hidden" value="<%= ticketKey %>" />
 
+			<c:if test="<%= SessionErrors.contains(request, NoSuchTicketException.class.getName()) %>">
+				<div class="alert alert-warning">
+					<liferay-ui:message key="your-password-reset-link-is-no-longer-valid" />
+				</div>
+			</c:if>
+
 			<div class="alert alert-info">
 				<liferay-ui:message key="please-set-a-new-password" />
 			</div>
````

instead of redirecting the user to the "same" page?

**Comment by lipusz** [comment]
Anyway, thanks for working on this, Drew! :+1:

**Comment by drewbrokke** [comment]
You're welcome!  We thought it would be best to not render the form at all since the user would have no use for it without a valid ticket. Unless I misunderstand your suggestion...

**Comment by lipusz** [comment]
Hi Mika,

Do you think you can finish reviewing this today?

@mikakoivisto

**Comment by mikakoivisto** [comment]
I think I'll finish it tonight. I've been on and off the hospital since Sunday as our baby decided he wants out over 5 weeks early. Yesterday he finally came out. If I don't finish it today I'll pass it to Tomas.

**Comment by lipusz** [comment]
Whoa, Mika! I hope you're well now. And, congrats!  All the best for your
family and you!

On Thu, Sep 24, 2015 at 11:13 AM, Mika Koivisto <notifications@github.com>
wrote:

> I think I'll finish it tonight. I've been on and off the hospital since
> Sunday as our baby decided he wants out over 5 weeks early. Yesterday he
> finally came out. If I don't finish it today I'll pass it to Tomas.
>
> Sent from my iPhone
>
> > On Sep 24, 2015, at 11:09 AM, Tibor Lipusz <notifications@github.com>
> wrote:
> >
> > Hi Mika,
> >
> > Do you think you can finish reviewing this today?
> >
> > @mikakoivisto
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikakoivisto/liferay-portal/pull/104#issuecomment-142864261>
> .
>



-- 

*Tibor LIPUSZ*

Senior Software Engineer

Team Lead, Platform TS, EMEA
Security SME, Subscription Services & Release, Global


*Liferay Hungary Kft.* | H-1138 Budapest, Madarász Viktor u. 47. a-b.,
Hungary

*Visit Us: **www.liferay.com <http://www.liferay.com/>**  |  Like Us:
**facebook.com/liferay
<http://facebook.com/liferay>**  |  Follow Us: twitter.com/liferay
<http://twitter.com/liferay>*


* <http://twitter.com/liferay>*

<http://www.liferay.com>

**Comment by drewbrokke** [comment]
Wow, congratulations, Mika!  Our baby did the same thing :)

**Comment by mikakoivisto** [comment]
I did some minor refactoring and sent it Brian. See https://github.com/brianchandotcom/liferay-portal/pull/30518

**Pull request closed without merging**
